name: Auto Tag on Version Change

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'package.json'

permissions:
  contents: write
  actions: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Получение версии из package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Проверка существования тега
        id: check-tag
        run: |
          if [ $(git tag -l "v${{ steps.package-version.outputs.current-version}}") ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Создание тега
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ steps.package-version.outputs.current-version}}" -m "Release v${{ steps.package-version.outputs.current-version}}"
          git push origin "v${{ steps.package-version.outputs.current-version}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 