name: Release Workflow

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'package.json'

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.create_tag.outputs.tag_exists }}
      version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Получение версии из package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Создание тега
        id: create_tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [ $(git tag -l "v${{ steps.package-version.outputs.current-version}}") ]; then
            echo "Tag already exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            git tag -a "v${{ steps.package-version.outputs.current-version}}" -m "Release v${{ steps.package-version.outputs.current-version}}"
            git push origin "v${{ steps.package-version.outputs.current-version}}"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

  build-mac:
    needs: create-tag
    if: needs.create-tag.outputs.tag_exists == 'false'
    runs-on: macos-latest
    
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Установка зависимостей
        run: npm install

      - name: Сборка для macOS
        env:
          GH_TOKEN: ${{ github.token }}
        run: npm run build:mac

      - name: Загрузка артефактов в релиз
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{ needs.create-tag.outputs.version }}
          files: |
            dist/*.dmg
            dist/*-mac.zip
          draft: false
          prerelease: false
          generate_release_notes: true

  build-windows:
    needs: create-tag
    if: needs.create-tag.outputs.tag_exists == 'false'
    runs-on: windows-latest
    
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Установка зависимостей
        run: npm install

      - name: Сборка для Windows
        env:
          GH_TOKEN: ${{ github.token }}
        run: npm run build:win

      - name: Загрузка артефактов в релиз
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{ needs.create-tag.outputs.version }}
          files: dist/*.exe
          draft: false
          prerelease: false
          generate_release_notes: true 