name: Release Workflow

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'package.json'

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.create_tag.outputs.tag_exists }}
      version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Получение версии из package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Создание тега
        id: create_tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [ $(git tag -l "v${{ steps.package-version.outputs.current-version}}") ]; then
            echo "Tag already exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            git tag -a "v${{ steps.package-version.outputs.current-version}}" -m "Release v${{ steps.package-version.outputs.current-version}}"
            git push origin "v${{ steps.package-version.outputs.current-version}}"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: create-tag
    if: needs.create-tag.outputs.tag_exists == 'false'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
    
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Установка зависимостей
        run: npm install

      - name: Сборка для macOS (Universal)
        if: matrix.os == 'macos-latest'
        run: |
          npm run build:mac

      - name: Сборка для Windows
        if: matrix.os == 'windows-latest'
        run: |
          npm run build:win

      - name: Загрузка артефактов в релиз
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.create-tag.outputs.version }}
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true 